# Generated by Django 2.1.3 on 2018-11-19 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tokenauth', '0003_auto_20181119_0343'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHasPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='custompermission',
            name='users',
        ),
        migrations.AddField(
            model_name='userhaspermission',
            name='permissions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_perms', to='tokenauth.CustomPermission'),
        ),
        migrations.AddField(
            model_name='userhaspermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_perms', to=settings.AUTH_USER_MODEL),
        ),
    ]
